# This docker-compose file is used for development purposes
# so that we can spin up the services locally in Docker quickly

version: '3'
services:
  user-service:
    build:
      context: ./user-service 
      dockerfile: Dockerfile.dev
    # ports:
    #   - "8080:8080"
    network_mode: host
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile.dev
    # ports:
    #   - "8090:8090"
    network_mode: host
  matching-service:
    build: 
      context: ./matching-service
    # ports:
    #   - "5003:5003"
    network_mode: host
  collaboration-service:
    build: 
      context: ./collaboration-service
    # ports:
    #   - "5001:5001"
    network_mode: host

# We use network_mode host to allow communication BETWEEN service containers via localhost
# However, this currently doesn't work on MacOS, will work on Windows
# https://github.com/docker/for-mac/issues/2716