# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: matching-service-test

on:
  push:
    branches: [ "main" ]
    paths: 
      - "matching-service/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "matching-service/**"

jobs:
  test:
    name: Matching Service test 
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: matching-service
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        yarn 
        yarn test
