# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cs3219-project-ay2223s1-g50-question-service-test

on:
  push:
    branches: [ "main" ]
    paths: 
      - "question-service/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "question-service/**"

jobs:
  test:
    name: Question Service test 
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: question-service
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        npm ci
        npm test
        echo ${{ github.repository.owner}}
