# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cs3219-project-ay2223s1-g50-user-service-test

on:
  push:
    branches: [ "main" ]
    paths: 
      - "user-service/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "user-service/**"

jobs:
  test:
    name: User Service test 
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: user-service
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        echo ${{ github.repository.owner}}
        npm ci
        npm test

